name: Build and test
env:
  image_tagged: laravel-realworld-example-app
  default_port: 5000
  source_image: tmp-cnb-image
on:
  push: {}
jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build using heroku/buildpacks:20 CNB
        uses: dfreilich/pack-action@v2.0.0
        with:
          args: 'build ${{ env.source_image }} --builder heroku/buildpacks:20'
      - name: Add default port to image
        run: |
          cat >> Dockerfile <<EOF
          ARG source_image
          FROM ${source_image}
          ARG default_port
          ENV PORT=${default_port}
          EXPOSE ${default_port}
          EOF
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            default_port=5000
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/acdh-oeaw/${{ env.image_tagged }}
# acdhch/${{ env.image_tagged }}            